[project]
name = "sparsemodesnet"
requires-python = ">= 3.11"
version = "0.1.0"
dependencies = ["kneeliverse>=1.0,<2"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tool.pixi.pypi-dependencies]
sparsemodesnet = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
black = ">=25.1.0,<26"
pytorch = ">=2.7.0,<3"
numpy = ">=2.2.6,<3"
torchvision = ">=0.22.0,<0.23"
pandas = ">=2.2.3,<3"
matplotlib = ">=3.10.3,<4"
tqdm = ">=4.67.1,<5"
jupyter = ">=1.1.1,<2"
scipy = ">=1.15.2,<2"
kneed = ">=0.8.5,<0.9"
jax = ">=0.6.0,<0.7"
absl-py = ">=2.3.0,<3"

[dependency-groups]
test = ["pytest"]
